aiken-lang/aiken

crates/uplc/src/program_builder/constant.rs

Turns out `char` isn't part of the spec anymore. See spec [here](https://cdn.discordapp.com/attachments/967217093688836137/995509973683552316/plutus-core-specification-june2022.pdf).
This means #18 is no longer relevant and this TODO commented code needs to be removed.

Remove TODOs related to closed story

---

Cargo.lock
crates/flat/Cargo.toml
crates/flat/src/encode/encoder.rs
crates/flat/src/lib.rs
crates/flat/src/zigzag.rs
crates/flat/tests/flat_test.rs
crates/flat/tests/zigzag_test.rs

First issue on this repo.
I was improving the `write_blk` function which previously implemented using recursive function and pointer arithmetic. Turns out there is no test case for large input for Encode trait. Therefore I add some test cases to test it.
And also fixed some weird bug on the zig zag encoding.
So it should be working for now.
PS: is it okay to introduce dependency [bumpalo](https://github.com/fitzgen/bumpalo)? I see there are a lot of vector push so I suspect apply this and there will be performance improvement. (of course, benchmark is needed)

Proptest added, found bug on encoding bytes input larger than 255 bytes.

---

crates/cli/src/main.rs

During the evaluation of a smart contract script, the user may invoke trace to generate a debug log as a side-effect.
This may be made optional with a --verbose flag, but usually the user wants to see all invocations of the Trace command.
Just not showing the content is very confusing, as the user would expect any kind of output when Trace is invoked (I for example need this when evaluating the execution path of transpiled Imperator/PySCC programs)

Print machine logs (debug trace)

---

crates/uplc/src/parser.rs
crates/uplc/src/pretty.rs

The [UPLC documentation](https://github.com/input-output-hk/plutus/blob/master/plutus-core-spec/draft-new-specification/plutus-core-specification.pdf) and [its implementation](https://github.com/input-output-hk/plutus/blob/master/plutus-core/plutus-core/src/PlutusCore/Parser/Builtin.hs#L91) explicitely do not support the parsing of PlutusData constants in UPLC notation.
Being able to pass PlutusData into uplc is extremely handy though and a necessary feature for most useful contracts. I therefore suggest to implement a notation standard for PlutusData constants in uplc:
```
(con data #0000)
```
where `#0000` is the CBOR hex representation of a valid PlutusDatum.
This has the benefit of not requiring to introduce parsing/printing for the vast (and still unreadable) constructors etc of …

UPLC data parsing support by CBOR notation

---

crates/uplc/src/machine/error.rs
crates/uplc/src/machine/runtime.rs

Applying an accidental wrong datum/redeemer to the tx lets the machine panic. From the WASM side it's really hard to understand what happened. This error handling helps with what's going on.

Added deserialisation error to machine

---

CHANGELOG.md
crates/cli/src/main.rs

fix the cbor_hex flag for `aiken uplc flat`

---

crates/lsp/src/error.rs
crates/lsp/src/lib.rs
crates/lsp/src/server.rs

The problem was that the edits don't exist in the FS. There is a notification for handling document edits and we have to use this to track files with edits. On format we look for the file in `self.edited` before pulling it from the FS.
closes #98

Fix LSP formatting

---

CHANGELOG.md
crates/lang/src/format.rs
crates/lang/src/parser.rs
examples/sample/validators/swap.ak

the parser can now fill in a label for unlabeled fields in a record. Before no label meant it was treated as a positional, so there were strange cases that didn't infer the right types for the right fields because the typechecker assumed it was a positional CallArg.

More record sugar in patterns

---

crates/cli/src/cmd/fmt.rs

When you enter `aiken --help` the `fmt` text is `Create a new Aiken project` which is the same text as the text from the `new` subcommand.
This PR updates the help text to say `Format an Aiken project`.

Update `aiken fmt` help text to "Format an Aiken project" from "Create a new Aiken project"

---

book/src/uplc/builtins.md
book/src/uplc/syntax.md
crates/uplc/src/parser.rs
crates/uplc/src/pretty.rs

Supersedes #35.
The syntax for these elements isn't "set in stone"; in the sense that it is unspecified in [input-output-hk/plutus](https://github.com/input-output-hk/plutus). There's no visible plan from IOG to extend the Haskell parser to support this syntax, though there are samples of imagined syntax in the code. Thus, we can lead the way and simply choose a suitable syntax and let the Haskell implementation align to it later.
This syntax is thus inspired from input-output-hk/plutus' samples, with only a small change: we use `<` and `>` for encapsulating type declaration instead of `(`, `)`. There are already enough parentheses in the UPLC syntax, adding more reduces visibility.
Doing this, I've also added a lot more test cases for the UPLC parser. There could be more, but this is a …

Add UPLC support for 'ProtoList' & 'ProtoPair' constants

---

crates/project/src/lib.rs
crates/project/src/options.rs

I've created a new struct and enum for handling the different modes the code gen can be used under. This is a bit cleaner than the spider web of bools we were starting to accumulate.

Refactor compile options

---

crates/lang/src/format.rs
crates/lang/src/parser.rs
crates/lang/src/tests/parser.rs
examples/sample/validators/swap.ak

* generics now use chevrons `Option<Int>`
* no longer need a `#` in front of tuples `(1, 2, 3)`

Chevron for Generics

---

crates/cli/src/cmd/check.rs
crates/project/src/lib.rs
crates/project/src/options.rs

For running only tests matching a certain pattern. Useful when doing TDD.
For example:
```
aiken check --match-tests list
```

Add --match-tests to 'check' cmd

---

crates/lang/src/parser.rs
crates/lang/src/parser/lexer.rs
crates/lang/src/tipo/environment.rs
crates/lang/src/uplc.rs

This fixes ~two~ three things:
- :round_pushpin: **Enforce unique top-level names for tests too.**
This prevents the compiler from crashing later on. Test names should be unique and not clash with function names.
- :round_pushpin: **Preserve newlines after blocks of comments.**
This is an example of output from the formatter now:
```
//// Some module documentation
// foo
const a: Int = 42
// Some comment block
// For which newlines are respected.
// Foo
// Another one
/// add_one documentation
pub fn add_one(n: Int) -> Int {
// n + 1
n + 1
}
```
before this commit, comments would all be collapsed into one group
above the function as:
```
// Some comment block
// For which newlines are respected.
// Foo
// Another one
/// add_one documentation
pub fn add_one(n: Int) -> Int {
```
- …

Some fixes

---

crates/cli/src/cmd/new.rs

Small updates to the template files used by `aiken new`. I noticed that running `aiken build` would generate errors, so I made the following updates:
- Update generics syntax
- Add required args to default validator function
This allows running a successful `aiken build` directly after `aiken new`.

Fix errors on aiken build

---

crates/lang/src/parser.rs
crates/lang/src/parser/lexer.rs
crates/lang/src/parser/token.rs
crates/lang/src/tests/lexer.rs
examples/sample/validators/swap.ak

thanks to https://github.com/zesterer/chumsky/issues/230#issuecomment-1350845091
padded_by does mostly what padded would do but now instead we capture newlines ("\n") and emptylines ("\n\n") as special tokens.
EmptyLine's `span.start` goes into the ModuleExtra info.
NewLine token is simply filtered out while collecting comments and empty lines into ModuleExtra.

Properly capture empty lines

---

README.md

docs are now at https://aiken-lang.org

update link to docs in the readme

---

CHANGELOG.md
crates/uplc/src/tx/to_plutus_data.rs

Currently, `to_plutus_data()` for a post-Alonzo TxOut using a V1 script results in an incorrect PlutusData TxInfo as the tag on the datum part of the output is `121` when it should be `122`. This is because the code currently treats no datum hash as a `None::<DatumOption>`, but DatumOption did not exist in V1. Instead it should use the general `Option<A>` `to_plutus_data()` which this PR does (choose Hash<32> as this just aligns with the other match arm). At least, this is my understanding, but I am not 100% confident!

fix: correct V1 to_plutus_data() for post-alonzo txout with no datum hash

---

README.md

mdbook job no longer exists so this badge renders nothing

this badge no longer exists

---

crates/lang/src/tipo/environment.rs
crates/lang/src/tipo/error.rs
crates/lang/src/tipo/infer.rs

This is the most intuitive thing I could come up with: since the
problem is mainly due to the order in which we try declaring the
aliases, then it suffices to simply try as much as we can, and retry
on failure until there's no more failure.
Note that it's important to detect cycles if we do such thing (which
we can by noticing that a given iteration didn't make any progress).
It works pretty well in the end and even allow us to define a new kind
of type error should there be a cyclic definition.

Fix acceptance 021: allow registering type aliases in any order.

---

crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/tests/parser.rs
examples/sample/validators/swap.ak

Implicitly parse function params are `NamedLabeled`
closes #205

All function args are now labeled implicitly

---

Cargo.lock
crates/aiken-lang/Cargo.toml
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/levenshtein.rs
crates/aiken-lang/src/lib.rs
crates/aiken-lang/src/parser/error.rs
crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/fields.rs
crates/aiken-lang/src/tipo/pattern.rs
crates/aiken-lang/src/uplc.rs
crates/aiken-project/src/error.rs

- :round_pushpin: **Better errors when using unknown data-type constructor.**
```
× Checking
╰─▶ Unknown variable
Finite
╭─[../stdlib/validators/tmp.ak:10:1]
10 │   let now = when context.transaction.validity_range.lower_bound.bound_type is {
11 │     Finite { t } -> t
·     ────────────
12 │     NegativeInfinity -> 0
╰────
```
```
× Type-checking
╰─▶ Unknown data-type constructor 'Finite'
╭─[../stdlib/validators/tmp.ak:10:1]
10 │   let now = when context.transaction.validity_range.lower_bound.bound_type is {
11 │     Finite { t } -> t
·     ────────────
12 │     NegativeInfinity -> 0
╰────
help: Did you forget to import it?
Data-type constructors are not automatically imported, even if their type is
imported. So, if a module `aiken/pet` defines the following type:
┍━ aiken/pet.ak …
```

Better type check errors

---

crates/aiken-lang/src/air.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/parser/lexer.rs
crates/aiken-lang/src/parser/token.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/infer.rs
crates/aiken-lang/src/uplc.rs
crates/aiken/src/cmd/new.rs

* this adds the ability to say some branch of code should intentionally fail
```gleam
fn is_one(n: Int) -> Bool {
if n == 1 {
True
} else {
error
}
}
```
In a way this is similar to `todo` but it won't raise a compiler warning. Although the behavior of both are the same, they convey different "meaning"/intention to the programmer. `todo` should mean "I'll finish this later so it raises a warning". `error` should mean "this intentionally fails here".
closes #214

Error Keyword

---

crates/uplc/src/tx.rs
crates/uplc/src/tx/eval.rs

Before each redeemer had the full budget for evaluation, which was not fully correct. All redeemers combined can consume the full budget, not each one individually. 
Now each redeemer takes the remaining budget as argument instead of the full budget.

Fixed ex units budget limit per redeemer

---

crates/aiken-project/src/lib.rs
crates/aiken-project/src/options.rs
crates/aiken/src/cmd/check.rs

`--match-tests` idea
allow it to take a list of what looks like a regular aiken import
`aiken check --match-tests "aiken/option.{flatten, map}" --match-tests aiken/list`
- can match an entire module `aiken/list`
- can match on an exact test name `aiken/option.{flatten_2}`
- can do a fuzzy match on test names `aiken/option.{flatten}`
- this would run all 4 flatten tests

`aiken check` make match tests flag fancier

---

crates/aiken-lang/src/format.rs

- `error("some message")` was getting formatted to `error` which is rather rude of the formatter

error fmt was removing label

---

crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/pattern.rs

We just need to set it to `args.len()`
`I saw a pattern on a constructor that has 1 fields be matched with 0 arguments.`

IncorrectArity - the expected arity with hardcoded to 0

---

crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/parser/token.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/parser.rs

This changes allow to use parenthesis `(` `)` to encapsulate
expressions in addition to braces `{` `}` used to define blocks.
The main use-case is for arithmetic and boolean expressions for which
developers are used to using parenthesis. For example:
```
{ 14 + 42 } * 1337
```
can now be written as:
```
( 14 + 42 ) * 1337
```
This may sound straightforward at first but wasn't necessarily trivial
in Aiken given that (a) everything is an expression, (b) whitespaces
do not generally matter and (c) there's no symbol indicating the end
of a 'statement' (because there's no statement).
Thus, we have to properly disambiguate between:
```
let foo = bar(14 + 42)
```
and
```
let foo = bar
(14 + 42)
```
Before this commit, the latter would be interpreted as a function call
and would lead to a …

Support (and default to) parenthesis for block expressions

---

crates/aiken-project/src/deps/downloader.rs
crates/aiken-project/src/deps/manifest.rs
crates/aiken-project/src/error.rs
crates/aiken-project/src/paths.rs
crates/aiken/src/cmd/deps/clear_cache.rs
crates/aiken/src/cmd/deps/mod.rs
crates/aiken/src/cmd/mod.rs
crates/aiken/src/main.rs

- :round_pushpin: **Invalidate cache using etag for deps by branch**
Aiken's build system uses an internal global cache system to avoid
downloading the same packages over and over across projects. However,
prior to this commit, the cache key would be based of the dependency
version which can be either:
- A commit hash
- A branch or tag name
However, in the latter case, it means that the very first time we end
up fetching a dependency will lock its version forever (or until the
cache is cleared). This was inconvenient.
This commit changes that so that we use not only a branch name as
cache key, but additionally, the etag returned by the GitHub API
server. The etag is part of the HTTP headers, so it can be fetched
quickly using a simple HEAD request. It changes whenever the content
behind …

Deps and cache manipulation

---

crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lang/src/tipo/error.rs

closes #81 
We do not want to allow users to import validator modules. They are special modules for defining validator functions that correspond to one of the four script purposes.
I've also added a help message that instructs people to move the code they want to share to a new module in `lib/`.

Error for when a validator module is imported

---

crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken/src/lib.rs

closes #271 
Implicitly discarded expressions make no sense to allow
```
pub fn stuff() -> Int {
do_other_stuff()
1
}
```
Currently the underlined area seems to be incorrect, will need to investigate that further

Error for when an expression is implicitly discarded

---

crates/aiken-lang/src/builder.rs
crates/aiken-lang/src/tipo.rs

Fixed variant name issue
Due to seriousness of issue I ignored resolving test 45. Will work on after

fix: get_variant_name was not properly traversing type args on map and data uplc types

---

crates/aiken-lang/src/format.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs

- :round_pushpin: **Remove dead-code and fix comment about discarded expressions**
While Gleam originally allowed various kinds of expressions to be discarded in a sequence, we simply do not allow expressions to be discarded implicitly. So any non-final expression in a sequence must be a let-binding. This prevents silly mistakes.
- :round_pushpin: **slightly rework hint for 'ImpliclyDiscardedExpression'**
- :round_pushpin: **Fix typo in variant name: Implicity -> Implicitly**
- :round_pushpin: **Forbid let-binding as last expression of a sequence**
Fixes #283

Forbid assignment as last expression

---

crates/aiken-lang/src/parser/lexer.rs
crates/aiken-lang/src/tests/parser.rs

closes #309 
* This should fix the parser issues on windows
* `\r\n` needed to be captured as a NewLine
* `\r\n\r\n` needed to be captured as an empty line
* I do not have access to a windows machine to test this

Windows capture carriage return properly

---

crates/aiken-lang/src/air.rs
crates/aiken-lang/src/builder.rs
crates/aiken-lang/src/tipo.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/uplc.rs
crates/uplc/src/ast/builder.rs
crates/uplc/src/machine.rs
crates/uplc/src/machine/error.rs
examples/acceptance_tests/040/lib/tests.ak

- Minor fix to head list in function list_access_to_uplc
- Assert is fleshed out to recursively check a type cast
- Clean up unused Air and categorically order Air
- Refactoring to reduce code reusage
- Safe guard against type casting without a left hand type annotation
- Found a great use case for choose_unit :P
- Added handling of single clause when for acceptance test 48

Assert data type to type cast

---

crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/parser/token.rs
crates/aiken-lang/src/tipo/infer.rs

There was some discussion a little while back and we realized that having `check` just makes things in regards to assignment confusing. We also decided that `assert` might as well also do the extra things `check` was going to to anyways.
assert now have the following behaviour:
1. if asserting and casting on `Data` then the structure is recursively checked
2. if it's not a type cast then it only checks the constr index

remove check assignment

---

Cargo.lock
crates/aiken-lang/src/uplc.rs
crates/aiken-project/src/blueprint/validator.rs
crates/uplc/Cargo.toml
crates/uplc/src/ast.rs
crates/uplc/src/lib.rs
crates/uplc/src/optimize.rs
crates/uplc/src/optimize/shrinker.rs

Reduces unneeded lambdas that assign a value once, or assign a var or constant
Forces on builtins are prewrapped to only cost you once.
Closes #323 
Closes  #324 
Closes #325 
Closes #326

Force and lambda optimizations

---

crates/uplc/src/pretty.rs

This attempts to fix #328 but beware, is 100% untested.

Add missing carets when dumping builtin list

---

Cargo.lock
crates/uplc/Cargo.toml
crates/uplc/src/machine/error.rs
crates/uplc/src/machine/runtime.rs

I'm not particularly happy with this but it seems to work. People can now disable default features and enable wasm as a feature on the `uplc` crate. This will swap which library is being used for ecdsa and schnorr verification so that things can still compile to wasm.

allow verify functions to build for wasm

---

crates/aiken-lang/src/builder.rs
crates/uplc/src/machine/runtime.rs
crates/uplc/src/tx/to_plutus_data.rs

This fixes the constructor indices and allows the usage of any index number according to specs.

Fix constructor tag range

---

Cargo.lock
crates/aiken-lang/src/builder.rs
crates/aiken-lang/src/uplc.rs
crates/uplc/Cargo.toml
crates/uplc/src/ast.rs
crates/uplc/src/flat.rs
crates/uplc/src/machine.rs
crates/uplc/src/machine/error.rs
crates/uplc/src/machine/runtime.rs
crates/uplc/src/parser.rs
crates/uplc/src/program_builder/constant.rs

closes #355
We decided to go with [num-bigint](https://docs.rs/num-bigint/latest/num_bigint/struct.BigInt.html#impl-From%3Ci128%3E).
We started by replacing `Constant::Integer(i128)` with `Constant::Integer(BigInt)`.
This resulted in a need for a new way to get the `integer_log2` of `Constant::Integer` in `machine::Value::to_ex_mem`.
We've added some tests to the bottom of the `machine` module.
It was pretty easy/simple to go from a string to bytes to `BigInt` when parsing.
For the flat decoding/encoding is seemed appropriate to just cast `BigInt` to and from `i128` which made things very simple.
It seemed unlikely that people will have hardcoded constant larger than that, which is really the only situation where you'd find yourself decoding/encoding a `Constant::Integer`

Upgrade Term::Constant to use BigInt

---

crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tests/mod.rs
crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/pattern.rs
crates/aiken-lang/src/uplc.rs

- :round_pushpin: **Basic exhaustivness check on list patterns**
Before that commit, the type-checker would allow unsafe list patterns
such as:
```
let [x] = xs
when xs is {
[x] -> ...
[x, ..] ->  ...
}
```
This is quite unsafe and can lead to confusing situations. Now at
least the compiler warns about this. It isn't perfect though,
especially in the presence of clause guards. But that's a start.
- :round_pushpin: **Add missing newlines to 'join' in error messages.**
- :round_pushpin: **Add type-checker sanity tests for list patterns.**
- :round_pushpin: **Remove patterns on 'String'**
There's arguably no use case ever for that in the context of on-chain
Plutus. Strings are really just meant to be used for tracing. They
aren't meant to be manipulated as heavily as in classic programming …

Patterns improvements

---

crates/aiken-lang/src/uplc.rs
examples/acceptance_tests/040/lib/tests.ak

Add more coverage to acceptance test 40 on expect
Lists with expect check for exact items in list patterns with no tail.
Constructors with expect check for contructor index in a constructor pattern

Change how expect works on lists and constructors

---

Cargo.lock
crates/aiken-lang/Cargo.toml
crates/aiken-lang/src/air.rs
crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/builder.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/parser.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/uplc.rs
examples/acceptance_tests/032/lib/tests.ak

- :round_pushpin: **Allow to trace expressions (and not only string literals)**
This however enforces that the argument unifies to a `String`. So this
is more flexible than the previous form, but does fundamentally the
same thing.
Fixes #378.
- :round_pushpin: **Lift 'error' up one level in the parser and remove its label.**
We now parse errors as a combination of a trace plus and error term. This is a baby step in order to simplify the code generation down the line and the internal representation of todo / errors.
- :round_pushpin: **Remove 'Todo' from the AST & AIR**
Todo is fundamentally just a trace and an error. The only reason we kept it as a separate element in the AST is for the formatter to work out whether it should format something back to a todo or something else.
However, …

Trace rework and unification

---

Cargo.lock
crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/tipo.rs
crates/aiken-lsp/Cargo.toml
crates/aiken-lsp/src/cast.rs
crates/aiken-lsp/src/lib.rs
crates/aiken-lsp/src/server.rs
crates/aiken-lsp/src/server/lsp_project.rs
crates/aiken-lsp/src/server/telemetry.rs
crates/aiken-lsp/src/utils.rs
crates/aiken-project/src/blueprint/validator.rs
crates/aiken-project/src/config.rs
crates/aiken-project/src/error.rs
crates/aiken-project/src/format.rs
crates/aiken-project/src/lib.rs
crates/aiken-project/src/module.rs
crates/aiken-project/src/paths.rs
crates/aiken-project/src/telemetry.rs
crates/aiken/src/cmd/blueprint/apply.rs
crates/aiken/src/cmd/fmt.rs
crates/aiken/src/lib.rs

closes #110 
A big round of improvements for the LSP server. I once again borrowed a lot from gleam.
* I've disabled completions because they weren't behaving the way I wanted and I want to work on other things for now. I'll come back to completions a little later.
* I moved the attach doc method to be on CheckedModule instead to delay a bit when that computation needs to happen

Lsp Improvements

---

crates/aiken-project/src/blueprint/schema.rs
crates/aiken-project/src/blueprint/validator.rs

```
type State {
extra: Data,
}
```
was not allowed to be a datum before this change. We weren't sure what the best solution is, so we'll wait for commentary from @KtorZ before proceeding.

Data was not allowed in an interface

---

CHANGELOG.md
crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lang/src/tipo/error.rs

closes #433 
* Removed some code that looked for other variants that had matching field labels and types. This was allowing a field access edge case to cause code gen issues.
* If a type has more than one constructor we just early return the field accessors `Vec` as empty

restrict record field access to single constructor types

---

crates/aiken-project/src/blueprint/definitions.rs
crates/aiken-project/src/blueprint/mod.rs
crates/aiken-project/src/blueprint/schema.rs
crates/aiken-project/src/blueprint/validator.rs
crates/aiken-project/src/lib.rs
crates/aiken/src/cmd/blueprint/convert.rs
examples/acceptance_tests/036/plutus.json
examples/acceptance_tests/047/plutus.json
examples/acceptance_tests/048/plutus.json
examples/acceptance_tests/071/plutus.json
examples/hello_world/plutus.json

Fixes #416 
- :round_pushpin: **Add failing test scenario for recursive types.**
- :round_pushpin: **Make blueprint code slightly more resilient to changes.**
Leverage traits instead of hard-coded type parameters.
- :round_pushpin: **Introduce indirection for fields.**
- :round_pushpin: **Fix blueprint generation for recursive types.**
This was a bit tricky and I ended up breaking things down a lot and
trying different path. This commit is the result of the most
satisfying one.
It introduces a new 'concept' and types: Definitions and Reference.
These elements are meant to reflect JSON pointers and JSON-schema
definitions which we now use for pretty much all user-defined
data-types.
In fact, Schemas are no longer inlined, but are always referencing
some schema under "definitions".
This …

Handle recursive type definitions in blueprint

---

crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/parser/token.rs
crates/aiken-lang/src/pretty.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/parser.rs
crates/aiken-lang/src/tipo/expr.rs

Fixes #442 
- :round_pushpin: **Support flexible pipe operator formatting**
Rules are now as follows:
- If a pipeline contains a newline, then the entire pipeline is formatted over multiple lines.
- If it doesn't, then it's formatted as a single-line UNLESS it cannot fit; in which case, we fallback to multiline again.
- :round_pushpin: **Remove unused 'FlexBreak'**
The difference between 'FlexBreak' and 'Break(Mode::Strict/Flexible)' as always confused me; and turned out that the 'FlexBreak' thingy is never used. This is dead-code, so I removed it.

Flexible pipe operator

---

crates/aiken-lang/src/tipo/error.rs

print todo's type when printing the todo warning

---

CHANGELOG.md
crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/hydrator.rs

It is now possible to leave a hole in a type annotation and have the compiler fill-in the expected type of us. This is a pretty useful debugging tool when playing with complex functions.
Fixes #449

Provide better compiler feedback for type holes in annotations.

---

crates/uplc/src/tx/error.rs

fixes https://github.com/spacebudz/lucid/issues/166
It seems this is still safe to do because `tx simulate` explicitly matches on this error anyways.
Bringing this back sorts out an issue that was reported via lucid.
The other option would be to just have this same format string in an extra match in `lucid` where it uses `eval_phase_two_raw`

Lucid Issue

---

flake.nix

This is a sticking plaster  
Otherwise hit 
```
error[E0658]: let...else statements are unstable
```
I don't know why cargo2nix seems to be so far behind rustc.

bump rustc version for nix

---

crates/aiken-lang/src/gen_uplc.rs
crates/uplc/src/optimize.rs

In when statements and let the value shared a common ancestor with expressions below. Now the value will not have a common ancestor with expressions below.

fix: Scope issues caused by common ancestor scope being the value instead of the assignment

---

Cargo.lock
crates/aiken-lang/src/tipo.rs
crates/aiken-project/Cargo.toml
crates/aiken-project/src/blueprint/definitions.rs
crates/aiken-project/src/blueprint/error.rs
crates/aiken-project/src/blueprint/mod.rs
crates/aiken-project/src/blueprint/parameter.rs
crates/aiken-project/src/blueprint/schema.rs
crates/aiken-project/src/blueprint/validator.rs
crates/aiken-project/src/lib.rs
crates/aiken/src/cmd/blueprint/apply.rs
crates/aiken/src/cmd/blueprint/convert.rs
crates/uplc/src/ast.rs
crates/uplc/src/builder.rs

- :round_pushpin: **Write JSON deserializers for Reference, Constructors, Items and Data.**
This is needed in order to deserialize a JSON blueprint and use it to perform validation.
- :round_pushpin: **Impl JSON deserialization for blueprint's 'Schema'.**
- :round_pushpin: **Remove now-unnecessary blueprint generics.**
These were needed before as a way to _partially deserialize_
blueprints. Indeed, some commands required accessing information of
the blueprint, but not necessarily the schema. So out of laziness (or
cleverness?), we only deserialized validators as serde::Value and
achieved that through the use of generics.
Now that validators and schemas have proper deserialisers, we can
simply deserialize a blueprint.
TODO: Our serialisation/deserialisation is safe with regards to
itself; …

Blueprint schema validation

---

examples/gift_card/validators/multi.ak
examples/gift_card/validators/oneshot.ak

Update examples to use `from_minted_value`

Update: from_minting_value()

---

CHANGELOG.md
Cargo.lock
crates/aiken-lang/Cargo.toml
crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/parser/error.rs
crates/aiken-lang/src/parser/lexer.rs
crates/aiken-lang/src/parser/token.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/parser.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/pattern.rs

- :round_pushpin: **Introduce new test cases for hexadecimal and underscore parsing.**
- :round_pushpin: **Extend parser to support int as hexadecimal and numeric underscore.**
We only allow numeric underscore for decimal numbers as I am not sure how we can define it for non-decimal numbers?
- :round_pushpin: **Refactor formatter to use new 'self.int' helper function.**
- :round_pushpin: **Preserve numeric underscore and hexadecimal notation through formatting.**
- :round_pushpin: **Complete CHANGELOG**
Fixes #592
Fixes #578

Hex and numeric underscore

---

CHANGELOG.md
crates/aiken-lang/src/gen_uplc.rs
crates/aiken-project/src/tests/gen_uplc.rs

Closes #607 
Closes #597 
fix: Issue where using var pattern in a when was passing the constr index instead of the constr
fix: Issue where expecting on a list had unexpected behaviors based on list length
fix: Issue where expecting on a list from data was using the wrong
expect cast for the list tail.

Issues fixes

---

CHANGELOG.md
crates/aiken/src/main.rs

If anything ever panics, which should include unwraps, then we present something that look like the image below. It's a bit more helpful than the default error that a user will see.
closes #525

add a panic hook, present issue link

---

CHANGELOG.md
crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/parser.rs
crates/aiken-lang/src/tipo/expr.rs

- :round_pushpin: **Refactor 'is_capture' field on function expressions.**
Refactored into an enum to make it easier to extend with a new variant to support binary operators.
- :round_pushpin: **Extend parser to accept anonymous binop as expressions.**
This is simply a syntactic sugar which desugarize to a function call with two arguments mapped to the specified binary operator.
Only works for '>' at this stage as a PoC, extending to all binop in the next commit.
- :round_pushpin: **Add remaining boolean comparison operator to anon binop parser.**
Nothing to see here as they all have the same signature. Implementing
arithmetic bin-operators and boolean logic operators will require some
more logic.
- :round_pushpin: **Support all binary operator in the anonymous binop parser.**
- …

First class binary operators

---

Cargo.lock
crates/aiken-lang/Cargo.toml
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/parser/extra.rs
crates/aiken-lang/src/tests/parser.rs
crates/aiken-project/Cargo.toml

Fixes #642 (maybe?)
- :round_pushpin: **Use byte count for token span in the lexer.**
Somehow, miette doesn't play well with spans when using chars indices.
So we have to count the number of bytes in strings / chars, so that
spans align accordingly.
- :round_pushpin: **Bump miette to 5.9.0**
No particular reason, but it's good to be up-to-date with our dependencies.

Fix span offset

---

.github/workflows/nix.yml

This removes one dependency of the project, by moving the Nix cache store into Github. There is no expected speed up, except for lower latency between the actions runner and the cache store.

chore: use magic-nix-cache instead of cachix

---

crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/parser/definition/function.rs
crates/aiken-lang/src/parser/definition/test.rs
crates/aiken-lang/src/parser/expr/error_todo.rs
crates/aiken-lang/src/parser/expr/mod.rs
crates/aiken-lang/src/parser/expr/sequence.rs
crates/aiken-lang/src/parser/expr/snapshots/error_basic.snap
crates/aiken-lang/src/parser/expr/snapshots/error_sugar.snap
crates/aiken-lang/src/parser/expr/snapshots/todo_basic.snap
crates/aiken-lang/src/parser/expr/snapshots/todo_sugar.snap
crates/aiken-lang/src/parser/expr/string.rs
crates/aiken-lang/src/parser/expr/when/clause.rs
crates/aiken-lang/src/parser/expr/when/snapshots/error_single_clause_no_message.snap
crates/aiken-lang/src/parser/expr/when/snapshots/todo_clause.snap
crates/aiken-lang/src/parser/expr/when/snapshots/todo_double_clause_no_message.snap

This was a bit more tricky than anticipated but played out nicely in
the end. Now we have one holistic way of parsing todos and errors
instead of it being duplicated between when/clause and sequence. The
error/todo parser has been moved up to the expression part rather than
being managed when parsing sequences. Not sure what motivated that to
begin with.
Fixes #621.

Fix todo/error parsing

---

crates/uplc/src/parser.rs
crates/uplc/src/pretty.rs
crates/uplc/tests/pretty_tests.rs

This is a WIP for #625;
This updates the pretty printing code to match the spec outlined here: https://github.com/input-output-hk/plutus/issues/4751#issuecomment-1538377273
There's no easy way that I could find to print PlutusData, or specifically BigInt's, so this isn't *fully* compliant yet.  Maybe some of this should be upstreamed into pallas? What do you think @scarmuega ?
Also, I need to update the parsing.  But I wanted to get some early feedback.

Update UPLC pretty printing / parsing to match plutus spec

---

CHANGELOG.md
crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser/definition/snapshots/def_test_fail.snap
crates/aiken-lang/src/parser/definition/test.rs
crates/aiken-lang/src/parser/expr/fail_todo.rs
crates/aiken-lang/src/parser/expr/mod.rs
crates/aiken-lang/src/parser/expr/snapshots/error_basic.snap
crates/aiken-lang/src/parser/expr/snapshots/error_sugar.snap
crates/aiken-lang/src/parser/expr/when/clause.rs
crates/aiken-lang/src/parser/expr/when/snapshots/when_clause_solo_error.snap
crates/aiken-lang/src/parser/lexer.rs
crates/aiken-lang/src/parser/token.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/snapshots/format_fail.snap
crates/aiken-lang/src/tests/snapshots/format_nested_function_calls.snap
crates/aiken-lang/src/tests/snapshots/format_trace_todo_error.snap
crates/aiken-project/src/tests/gen_uplc.rs
examples/acceptance_tests/script_context/validators/basic.ak
examples/acceptance_tests/script_context/validators/deploy.ak
examples/acceptance_tests/script_context/validators/mint.ak
examples/acceptance_tests/script_context/validators/withdrawals.ak

- We decided on discord that we're going to rename error to fail.
- I did things in such a way that the formatter will automatically fix this for people. At some point after a few releases we can remove `"error"` from the lexer.
- I even renamed `Token::ErrorTerm`. But I left `UntypedExpr::ErrorTerm` alone because there are some big changes in the Air tree branch that I don't want to cause conflicts with.
- Test definitions for expected failures have been updated as well `test name() fail {`. This is way more consistent with the new keyword and it ties in with the plans I have for the new `pure` keyword and `pure` function definitions. This kind of syntax is inspired by swift `func myFunc() throws -> String`. cc @KtorZ

rename `error` to `fail`

---

crates/aiken/src/cmd/blueprint/hash.rs
crates/aiken/src/cmd/blueprint/mod.rs

Similar to blueprint address and blueprint policy, this just prints the hash of the validator; useful if you need the hash, and you don't want to pipe the address to a bech32 decoder and juggle the hex.
Apologies for not opening a discussion first, but I figure it was similar enough to what we did elsewhere.
Also, technically this does a bit of redundant work by computing the address, then pulling out the hash, but this way I could reuse some code, and so I figured it was fine.

Add an aiken blueprint hash command

---

crates/aiken/src/lib.rs
flake.nix

* Update version on nix recipe
* Add some metadata
* (hopefully) Fix problem where if you add aiken as a NixOS package, it does not show on path
* Make build process just a little bit leaner
* Infer crate version from `aiken`'s Cargo.toml

Nix Updates

---

flake.nix

This PR add adds a nixpkgs overlay that allows nix users to add aiken to their `nixpkgs` reference, which is in many ways much easier to do than to actually export flake inputs to submodules. To use, you need to add the overlay to the listing, like so:
```nix
let
pkgs = import nixpkgs {
overlays = [ aiken.overlays.default ];
};
```

feat: add Nix Overlay

---

Cargo.lock
crates/aiken/Cargo.toml
crates/aiken/src/cmd/completion.rs
crates/aiken/src/cmd/mod.rs
crates/aiken/src/cmd/packages/add.rs
crates/aiken/src/main.rs
flake.nix

Adds a subcommand to generate shell completions. Should make the `aiken` cli tool more ergonomic.

feat: shell completions

---

crates/aiken-lsp/src/server.rs

This PR aims to fix two issues with vscode on windows:
1. Diagnostics do not show up as expected: canonicalizing the path makes it not match the original, so vscode doesnt know which file it is connected to and only shows issues in the "problems" pane.
2. Formatting fails because the path is url encoded and begins with a slash (resulting in file not found)

fix: LSP bugs on vscode+windows

---

crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser/expr/and_or_chain.rs
crates/aiken-lang/src/parser/expr/chained.rs
crates/aiken-lang/src/parser/expr/mod.rs
crates/aiken-lang/src/parser/expr/snapshots/and_chain.snap
crates/aiken-lang/src/parser/expr/snapshots/and_or_chain.snap
crates/aiken-lang/src/parser/expr/snapshots/or_chain.snap
crates/aiken-lang/src/parser/lexer.rs
crates/aiken-lang/src/parser/token.rs
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/snapshots/format_logical_op_chain.snap
crates/aiken-lang/src/tests/snapshots/format_nested_function_calls.snap
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs

A new syntax for writing long chains of `&&` and `||` binary operations. Even with some formatting `&&` and `||` chains can look a little ugly and be hard to clearly reason about. The new syntax also really helps with being able to visually disambiguate potentially confusing precedence in long BinOp chains.
```
and {
1 == 1,
True,
foo_bar,
}
```
```
or {
1 == 1,
and {
True,
2 == 3,
},
foo_bar
}
```

`and`/`or` chains

---

crates/aiken-project/Cargo.toml
crates/aiken-project/src/config.rs
crates/aiken-project/src/github/mod.rs
crates/aiken-project/src/github/repo.rs
crates/aiken-project/src/lib.rs

When running `aiken new` it tries to retrieve the latest release tag https://github.com/aiken-lang/aiken/issues/672#issue-1796508316, fallback to hardcoded value (eg. when there's no internet connection or Github server down, etc.)

`aiken new`: Try to get the latest tag of stdlib

---

CHANGELOG.md
crates/aiken/src/cmd/tx/simulate.rs
crates/uplc/src/tx/eval.rs
crates/uplc/src/tx/tests.rs

This PR changes the returned data structure from the `tx simulate` command. Instead of calculating the total execution budget from all the scripts inside the vector of redeemers, it returns a vector of ExBudgets.
The output for a single script is now
```bash
[{'mem': 443656, 'cpu': 171399581}]
```
and for multiscript
```bash
[{'mem': 568735, 'cpu': 212877955}, {'mem': 356523, 'cpu': 133054577}]
```
The order of the ExBudget vector should follow the order of the Redeemer vector.
I am still on the hunt for the fee issue. Any smart contracts that have fee logic always fail. But at least tx simulate can now handle multi-script transactions in a helpful way.

Enhance tx simulate

---

CHANGELOG.md
Cargo.lock
crates/aiken-project/src/blueprint/validator.rs
crates/aiken-project/src/lib.rs
crates/aiken-project/src/pretty.rs
crates/aiken/Cargo.toml
crates/aiken/src/cmd/blueprint/apply.rs
crates/uplc/src/ast.rs

- :round_pushpin: **Add some utility functions for displaying Term/PlutusData**
This is useful with the blueprint stuff, where Term are often just plain PlutusData.
- :round_pushpin: **Enable iterating over validator's parameters with a callback**
This is how we'll construct parameters interactively. We need to lookup the definition, and provide a data representation for it.
- :round_pushpin: **Add helper for splitting a long line into multiple lines.**
- :round_pushpin: **Support interactive blueprint parameter application.**
- :round_pushpin: **Refresh Cargo.lock & fill-in CHANGELOG.**

Interactive blueprint apply

---

crates/aiken-lang/src/gen_uplc.rs

Some refs using mut where I don't think they're needed. 
It's bit tricky to keep track of how the compilation pipeline works. 
I think within `CodeGenerator::build` only in calls to `self.assignment` is there a mutation. 
This PR isolates mutations a bit more.

rm unnecessary mut

---

crates/uplc/src/builder.rs

The method name looked dated. First commit changes it. 
It's actually not used at least within aiken --- possibly why it seemed to have out of date name. 
Second commit removes the method entirely which is maybe more appropriate. Dunno

rm unused pub func

---

CHANGELOG.md
crates/aiken-project/src/config.rs
crates/aiken-project/src/deps.rs
crates/aiken-project/src/deps/downloader.rs
crates/aiken-project/src/deps/manifest.rs
crates/aiken-project/src/error.rs
crates/aiken-project/src/lib.rs
crates/aiken-project/src/package_name.rs
crates/aiken-project/src/paths.rs
crates/aiken-project/src/telemetry.rs
crates/aiken/src/lib.rs
examples/hello_world/aiken.lock

This PR is meant to improve the UX around `aiken build`, especially when using unpinned dependency versions (e.g. `main`). I got bitten by that once again (and we've seen plenty of people being confused by that too) after I tried to rebuild some local package depending on `aiken-lang/stdlib@main`. 
Now, `aiken build` will actually try to resolve the latest version of any package that isn't specified by:
- a git sha
- a tag
If the upstream package has changed, then it is downloaded and updated locally such that using `main` actually means using `main`. The upstream package resolution is throttle to once an hour to avoid overloading Github with many calls for people using LSP. It also works fine when the network isn't available and will use the most recent version in the system cache that …

Improve UX around dependency fetching

---

CHANGELOG.md
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/pipe.rs
examples/hello_world/aiken.lock

This improves error messages for `a |> b(x)`.
We need to do a special check when looping over the args and unifying. This information is within a function that does not belong to pipe typer so I used a closure to forward along a way to add metadata to the error when the first argument in the loop has a unification error. Simply adding the metadata at the pipe typer level is not good enough because then we may annotate regular unification errors from the args.

Improve pipe type checking error messages

---

crates/aiken-lang/src/gen_uplc.rs
crates/aiken-lang/src/gen_uplc/builder.rs
crates/aiken-project/src/tests/gen_uplc.rs
crates/uplc/src/builder.rs
crates/uplc/src/machine.rs
crates/uplc/src/optimize/shrinker.rs

- sort alphabetically
- add some of the missing builtins used for ints
- renames some of the builtins and the functions that use them

Rationalize builder

---

crates/aiken-lang/src/format.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/snapshots/format_grouped_expression.snap
crates/aiken-lang/src/tests/snapshots/format_grouped_expression_2.snap
crates/aiken-lang/src/tests/snapshots/format_grouped_expression_3.snap
crates/aiken-lang/src/tests/snapshots/format_grouped_expression_4.snap
crates/aiken-lang/src/tests/snapshots/format_logic_op_with_code_block.snap
crates/aiken-lang/src/tests/snapshots/format_preserve_newline_after_bool_expect.snap
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
examples/gift_card/validators/multi.ak

closes #682 
I also found some code that panics in the formatter
```gleam
fn foo() {
y == { x |> f }
}
```
‘attempt to subtract with overflow’, crates/aiken-lang/src/format.rs:1158:59

formatter fixes

---

crates/aiken/src/cmd/uplc/encode.rs
crates/aiken/src/cmd/uplc/mod.rs
crates/aiken/src/cmd/uplc/shrink.rs

This exposes the UPLC optimization employed in the last step in the aiken compilation pipeline as a convenient command line application. A short test reveals that this can compress an [opshin](https://github.com/opshin/opshin) compiled contract from 26kb to 21kb. Trying to run optimizations on top of [plutonomy-cli](https://github.com/OpShin/plutonomy-cli) did not achieve any further shrinking beyond the 16kb reached by plutonomy-cli.
Nontheless, aiken uplc offers the benefit of being actively developed over plutonomy-cli. Moreover exposing this tool to third parties enables code reuse and may attract additonal developers to contribute to the aiken compilation pipeline (i.e. by porting features from plutonomy).

Add command line option to shrink uplc

---

crates/uplc/src/ast.rs

Since `eval_v1` was removed I need to use the `eval_version` method instead, but the `Language` type is a `pallas` type. Rather than depending on the same library version, it's easier to just reexport the type :)
I'm wondering if there is a lint for this sort of things: foreign types in public interfaces should be reexported.

Make foreign `Language` type publicly available

---

crates/aiken-lang/src/gen_uplc.rs
crates/aiken-lang/src/gen_uplc/builder.rs
crates/aiken-project/src/tests/gen_uplc.rs

Also implemented chooseunit for 0 args

Builtin.headlist fix for assoclists

---

crates/aiken/src/cmd/mod.rs

Improves the cli by adding aliases for the `build` and `check` commands, ensuring compatibility with Cargo's functionality.

Introduces cli aliases for `aiken check` and `aiken build` subcommands

---

README.md

Per Github docs (https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)
```
The old method of specifying images based on the theme, by using a fragment appended to the URL (#gh-dark-mode-only or #gh-light-mode-only), is deprecated and will be removed in favor of the new method described above.
```
There is a bug with Github if the theme settings are set to sync with system (xref: https://github.com/github/markup/issues/1583)

chore: use updated theme method

---

crates/aiken-project/src/blueprint/schema.rs
crates/aiken-project/src/blueprint/snapshots/aiken_project__blueprint__validator__tests__opaque_singleton_multi_variants.snap
crates/aiken-project/src/blueprint/snapshots/aiken_project__blueprint__validator__tests__opaque_singleton_variants.snap
crates/aiken-project/src/blueprint/validator.rs

Forbid opaque types in the application binary interface.

---

crates/aiken-project/src/lib.rs
crates/aiken-project/src/module.rs

- parse modules in parallel
- remove tests from the untyped modules of dependencies (also done in parallel)
- ignore warnings from dependency modules

Parallel Parsing

---

CHANGELOG.md
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs

Note: the stdlib still compiles, type-check and succeed on all tests.
Closes #827.

Forbid non-serializable inhabitants in compound data-types.

---

.gitignore
CHANGELOG.md
crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser/definition/snapshots/def_test_fail.snap
crates/aiken-lang/src/parser/definition/snapshots/function_assignment_only.snap
crates/aiken-lang/src/parser/expr/assignment.rs
crates/aiken-lang/src/parser/expr/snapshots/block_let.snap
crates/aiken-lang/src/parser/expr/snapshots/expect.snap
crates/aiken-lang/src/parser/expr/snapshots/expect_bool_sugar.snap
crates/aiken-lang/src/parser/expr/snapshots/expect_expect_let.snap
crates/aiken-lang/src/parser/expr/snapshots/expect_let_in_let.snap
crates/aiken-lang/src/parser/expr/snapshots/expect_let_in_let_parens.snap
crates/aiken-lang/src/parser/expr/snapshots/expect_let_in_let_return.snap
crates/aiken-lang/src/parser/expr/snapshots/expect_trace_if_false.snap
crates/aiken-lang/src/parser/expr/snapshots/function_invoke.snap
crates/aiken-lang/src/parser/expr/snapshots/int_numeric_underscore.snap
crates/aiken-lang/src/parser/expr/snapshots/let_bindings.snap
crates/aiken-lang/src/parser/expr/snapshots/parse_tuple.snap
crates/aiken-lang/src/parser/expr/snapshots/parse_tuple2.snap
crates/aiken-lang/src/parser/expr/when/snapshots/when_basic.snap
crates/aiken-lang/src/snapshots/function_ambiguous_sequence.snap
crates/aiken-lang/src/snapshots/parse_unicode_offset_1.snap
crates/aiken-lang/src/snapshots/parse_unicode_offset_2.snap
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/snapshots/format_many_assignment_patterns.snap
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs

The main trick here was transforming Assignment to contain `Vec<UntypedPattern, Option<Annotation>>` in a field called patterns. This then meant that I could remove the `pattern` and `annotation` field from `Assignment`. The parser handles `=` and `<-` just fine because in the future `=` with multi patterns will mean some kind of optimization on tuples. But, since we don't have that optimization yet, when someone uses multi patterns with an `=` there will be an error returned from the type checker right where `infer_seq` looks for `backpassing`. From there the rest of the work was in `Project::backpassing` where I only needed to rework some things to work with a list of patterns instead of just one.
This is what the new error looks like
This is what is looks like formatted with many args

backpassing multiple patterns

---

crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/builtins.rs
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tipo.rs
crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/infer.rs
crates/aiken-lang/src/tipo/pattern.rs
crates/aiken-lang/src/tipo/pretty.rs
crates/aiken-project/src/blueprint/snapshots/aiken_project__blueprint__validator__tests__opaque_singleton_multi_variants.snap
crates/aiken-project/src/blueprint/snapshots/aiken_project__blueprint__validator__tests__opaque_singleton_variants.snap

- added a new field called `opaque: bool` to `Type::App` (can be used to simplify some things in code gen too)
- implement a simple method on `Type` called `is_opaque` that leverages the new field
- make a new error for when someone uses expect with an opaque type in anyway
- catch this situation in `infer_assignment` and return the new error
> I figured that opaque does not need to affect the type equality

block expects on opaque types

---

crates/aiken-project/src/lib.rs
crates/aiken-project/src/module.rs

This changes ensure that we only compile modules from dependencies
that are used (or transitively used) in the project. This allows to
discard entire compilation steps at a module level, for modules that
we do not use.
The main goal of this change isn't performances. It's about making
dependencies management slightly easier in the time we decide whether
and how we want to manage transitive dependencies in Aiken.
A concrete case here is aiken-lang/stdlib, which will soon depend on
aiken-lang/fuzz. However, we do not want to require every single
project depending on stdlib to also require fuzz. So instead, we want
to seggregate fuzz API from stdlib in separate module, and only
compile those if they appear in the pruned dependency graph.
While the goal isn't performances, here are some …

Only compile modules the project depends on

---

crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tipo/environment.rs

We have been a bit too strict on disallowing 'allow_cast' propagations. This is really only problematic for nested elements like Tuple's elements or App's args. However, for linked and unbound var it is probably okay, and it certainly is as well for function arguments.

Allow downcasting to data in piped function calls.

---

crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/gen_uplc.rs
crates/aiken-lang/src/gen_uplc/air.rs
crates/aiken-lang/src/gen_uplc/tree.rs
crates/aiken-lang/src/parser/expr/fail_todo_trace.rs
crates/aiken-lang/src/parser/lexer.rs
crates/aiken-lang/src/parser/token.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-project/src/test_framework.rs

This adds the emit keyword (emissions) which is a kind of trace that is used for effectful offchain functionality and therefore should never be erased (even when Silent option to the keep traces flag is passed).
This is largely a UX feature to make it easier to implement the following pattern:
https://x.com/SebastienGllmt/status/1774479357370945544?s=20

feat: Emit keyword

---

LICENSE

Aiken will be a flagship project of the pragma organization. This has been a long time coming and as part of a kind of ceremonial hand off I've (@rvcas) created this pull request for the other maintainers (@KtorZ @MicroProofs) to sign off on (collectively known as the Aiken Council). This can be seen as a commitment from not only me but the whole Aiken team that this project belongs to the community. If things go well Aiken, will survive along with pragma long after various core maintainers come and go. There will be no change in the core team and we're all happily committed to working on Aiken for quite a while. That said, we intend on taking action on increasing the accessibility for external contributors. Special thank you to the @cardano-foundation for the continued support.
- …

moving to pragma

---

crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/infer.rs

- :round_pushpin: **Fix scope management issue when deep-inferring callee.**
Fixes #941.
However, this currently breaks the stdlib somehow with some FreeUnique on the shrinker step of the optimizer.
- :round_pushpin: **Also preserve warnings when resetting scope for backtracking.**
This is crucial as some checks regarding variable usages depends on
warnings; so we may accidentally remove variables from the AST as a
consequence of backtracking for deep inferrence.

Fix scope management issue when deep-inferring callee.

---

CHANGELOG.md
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/parser/definition/import.rs
crates/aiken-lang/src/parser/definition/mod.rs
crates/aiken-lang/src/parser/definition/snapshots/import_alias.snap
crates/aiken-lang/src/parser/definition/snapshots/import_basic.snap
crates/aiken-lang/src/parser/definition/snapshots/import_unqualified.snap
crates/aiken-lang/src/parser/utils.rs
crates/aiken-lang/src/snapshots/merge_imports.snap
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/snapshots/format_merge_imports.snap
crates/aiken-lang/src/tests/snapshots/format_merge_imports_2.snap
crates/aiken-lang/src/tests/snapshots/format_merge_imports_alias.snap
crates/aiken-lang/src/tests/snapshots/format_merge_imports_alias_2.snap
crates/aiken-lang/src/tests/snapshots/format_merge_imports_comments.snap

I slightly altered the way we parse import definitions to ensure we
merge imports from the same modules (that aren't aliased) together.
This prevents an annoying warning with duplicated import lines and
makes it just more convenient overall.
As a trade-off, we can no longer interleave import definitions with
other definitions. This should be a minor setback only since the
formatter was already ensuring that all import definitions would be
grouped at the top.
---
Note that, I originally attempted to implement this in the formatter
instead of the parser. As it felt more appropriate there. However, the
formatter operates on (unmutable) borrowed definitions, which makes it
annoyingly hard to perform any AST manipulations. The `Document`
returns by the format carries a lifetime that prevents …

Automatically merge import lines from same module.

---

.github/workflows/tests.yml
crates/aiken-lang/src/expr.rs
crates/aiken-project/src/test_framework.rs

* Correct the usage of a legacy numeric constant
* Update the checkout actions from 3 to  4 to use Node.js 20. This change should resolve the warning message.

chore(ci): Bump github actions/checkout from 3 to 4

---

flake.nix

The current nix expression doesn't build on either `aarch64-darwin` or `x86_64-darwin`, but with this small patch, it does.
Tested on:
- `aarch64-darwin`
- `x86_64-darwin`
- `x86_64-linux`

Solved: Nix expression broken in Darwin

---

crates/aiken-lang/src/gen_uplc.rs
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tipo.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/pattern.rs

> [!NOTE]
>
> See also the added test scenarios.
| code | before | after | 
| --- | --- | --- | 
| <img width="200" alt="image" src="https://github.com/user-attachments/assets/1b0635c4-a04e-478f-b0ba-73ed22474410"> | <img width="400" alt="image" src="https://github.com/user-attachments/assets/197dd697-4bea-4b03-93a9-6937351fa25b"> | <img width="400" alt="image" src="https://github.com/user-attachments/assets/af13023f-f562-47f4-999f-92dc8fd93776"> |
| <img width="200" alt="image" src="https://github.com/user-attachments/assets/0c671ccd-a2fb-4a86-8969-93815df41c4e">| <img width="400" alt="image" src="https://github.com/user-attachments/assets/93d6a4d9-19f3-40de-9b69-0d3a12243232"> | <img width="400" alt="image" src="https://github.com/user-attachments/assets/7b222c89-efaf-429c-a60b-3e2486ab7 …

Fix pattern inference and annotation requirements.

---

crates/aiken-lang/src/gen_uplc.rs
crates/aiken-lang/src/gen_uplc/builder.rs
crates/aiken-project/src/tests/gen_uplc.rs
crates/uplc/src/machine/runtime.rs

- :round_pushpin: **Support mk_cons builtin**
While this builtin is readily available through the Aiken syntax
`[head, ..tail]`, there's no reason to not support its builtin form
even though we may not encourage its usage. For completeness and to
avoid bad surprises, it is now supported.
Fixes #964.
- :round_pushpin: **Fix zero-arg builtins invokations.**
There are currently two zero-arg builtins:
- mkNilData
- mkNilPairData
And while they have strictly speaking no arguments, the VM still
requires that they are called with an extra unit argument applied.

Gen uplc builtin fixes

---

crates/aiken-lsp/src/utils.rs

Fixed hyphen in filename breaking LSP

---

CHANGELOG.md
crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/lib.rs
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/infer.rs
crates/aiken-lsp/src/server/lsp_project.rs
crates/aiken-project/src/config.rs
crates/aiken-project/src/error.rs
crates/aiken-project/src/lib.rs
crates/aiken-project/src/module.rs
crates/aiken-project/src/options.rs
crates/aiken-project/src/test_framework.rs
crates/aiken-project/src/tests/mod.rs
crates/aiken/src/cmd/blueprint/address.rs
crates/aiken/src/cmd/blueprint/hash.rs
crates/aiken/src/cmd/blueprint/policy.rs
crates/aiken/src/cmd/build.rs
crates/aiken/src/cmd/check.rs

Closes #937.
☝️  Many things happening on the image above:
- The project defines a bunch of _environments_ under the `env` directory. 
- The project defines an extra set of _configurations_ in its `aiken.toml`
- Tests make use of the special `env` and `config` modules, which are populated based on the `--env` flag. Defaulting to the environment/config called _default_ when not present.
- Tests are making conflicting assertions which can only pass in one of the given environment. As illustrated, since `--env preprod` is passed, only the preprod tests pass.
| Completely unknown | Close enough |  
| --- | --- | 
| <img width="472" alt="image" src="https://github.com/user-attachments/assets/110c0e70-8bd9-41c4-b6e3-f5d1d016fd16"> | <img width="501" alt="image" …

Conditional configuration & environment

---

crates/aiken-lang/src/tipo/expr.rs

This PR is to address the currently known issues around hover functionality for backpassing.
Unfortunately this is not a perfect fix, because of how nodes are looked for and the structure of the AST after handling backpassing.

Fixed span calculation for backpassing

---

examples/acceptance_tests/111/aiken.toml
examples/acceptance_tests/111/lib/foo.ak

Seems like nested tuples are inferred wrongly when type-casted.
```
type mismatch
Expected (list a)
Got integer
```

Add acceptance test 111

---

crates/uplc/src/machine/cost_model.rs

So in Conway the plutusV2 cost model was updated, but not the PlutusV1 cost model. 
This PR reflects the mainnet changes.

Update v2 cost models

---

flake.lock

nix builds using rustc 1.80 fail on (then) unstable features. 
This bumps to 1.82, and fixes this

bump flake deps

---

crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/gen_uplc/decision_tree.rs
crates/aiken-lang/src/test_framework.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/pretty.rs
crates/aiken-project/src/docs.rs
crates/aiken-project/src/error.rs
crates/aiken-project/src/package_name.rs
crates/aiken/src/cmd/completion/shell.rs
crates/uplc/src/flat.rs
crates/uplc/src/tx/to_plutus_data.rs
examples/acceptance_tests/115/aiken.toml
examples/acceptance_tests/115/validators/tests.ak

Deeply nested assignments would offset the new columns count calculation. Now we track relevant columns and their path to ensure each row has wildcards if they don't contain the relevant column

Fix: issue crash in code gen with incorrect column length in decision trees

---

crates/aiken-project/src/blueprint/definitions.rs
crates/aiken-project/src/blueprint/schema.rs
crates/aiken-project/src/blueprint/snapshots/aiken_project__blueprint__validator__tests__map_in_map.snap
crates/aiken-project/src/blueprint/snapshots/aiken_project__blueprint__validator__tests__pair_in_pair.snap
crates/aiken-project/src/blueprint/snapshots/aiken_project__blueprint__validator__tests__pair_used_after_map.snap
crates/aiken-project/src/blueprint/snapshots/aiken_project__blueprint__validator__tests__pair_used_before_map.snap
crates/aiken-project/src/blueprint/validator.rs

This ensures that we only prune unnecessary schema definitions from the blueprint when they truly are unnecessary. The first commit fixes #1086, but as we discussed internally, there's another problem we should find a resolution for (which I wish to include in this PR): currently, we generate schema for pairs as `#pairs`; which translates to a UPLC Term (not serializable as Data).  
So my first reaction was to simply forbid the presence of pairs in the contract ABI, but @MicroProofs pointed that part of the validator wrapper code includes conversion from lists of 2 elements to pairs (if types require it). Which means that pairs are _technically allowed_ in the contract ABI, but serialized as Data::List of two elements. 
Hence, the generated schema should reflect that; but only when pairs …

Fix blueprint pairs schema generation

---

crates/uplc/src/tx.rs

This PR adds updates to the `body_tx` decoding by era, so that the failing era's error get's passed down to the end result. Props to @SupernaviX for helping me through the code and debugging.

Better Error Logging

---

flake.lock
flake.nix

Required pinning hash of git dependency textplots

fix: nix builds

---

CHANGELOG.md
crates/aiken-lang/src/test_framework.rs
crates/aiken-project/src/telemetry/json.rs
crates/aiken-project/src/telemetry/terminal.rs
crates/aiken-project/src/tests/gen_uplc.rs
crates/aiken/src/cmd/tx/simulate.rs
crates/aiken/src/cmd/uplc/eval.rs
crates/uplc/src/ast.rs
crates/uplc/src/machine.rs
crates/uplc/src/machine/eval_result.rs
crates/uplc/src/machine/runtime.rs
crates/uplc/src/tx.rs
crates/uplc/src/tx/error.rs
crates/uplc/src/tx/eval.rs
crates/uplc/src/tx/tests.rs

This refactors things so that eval_phase_two can expose logs even when the script succeeds.
It also enriches traces to be either Logs or Labels, so that we can tell the difference between the two when inspecting the traces.
I was kind of changing things mechanistically, so let me know if you'd prefer anything changed!
I'm also not familiar with the changelog convention, so if someone could help me write a good changelog entry that would be helpful!

Return an EvalResult alongside the redeemer

---

Cargo.lock
crates/aiken-project/Cargo.toml
crates/aiken-project/src/telemetry/terminal.rs

this puts us in a situation where releasing incremental small changes is going to require much more special care than we should have.
WE MUST do it the same every time leaning on `cargo release` and allowing things to be uploaded to crates. We should not sacrifice this status quo for minor aesthetics. The bench feature is probably not wildly used at the moment anyways.
We also do not know when the upstream changes are going to be merged for textplot and I refuse to be in this broken release state for a long period of time. Any admin should be able to blindly run `cargo release` with no hand holding.
I have commented out the `.borders` call for now and left a todo comment reminding us to reintroduce the call once the pull request is merged and the crate is updated on crates.io

remove textplot fork for now

---

.github/workflows/tag.yml

pretty simple github action that installs cargo release and then runs it
the workflow is expected to be manually dispatched and capture what kind of `bump` to use with the cargo release command

new workflow to tag releases

---

Cargo.lock
Cargo.toml

No breaking/relevant changes, I'm just trying to fix a build issue in balius

chore: bump pallas to 0.32.0

---

CHANGELOG.md
crates/aiken-lang/src/tipo.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lsp/src/edits.rs
crates/aiken-lsp/src/lib.rs
crates/aiken-lsp/src/quickfix.rs
crates/aiken-lsp/src/server.rs
crates/aiken-lsp/src/utils.rs

- :round_pushpin: **Use less vertical space for type-constructor hint;**
Also, show it actually for UnknownTypeConstructor, and not UnknownVariable. There's currently an error that wrongly assign an 'UnknownVariable' in place where it should be an 'UnknownTypeConstructor'. Fix coming in the next commit.
- :round_pushpin: **Fix wrong use of 'UnknownVariable' instead of 'UnknownTypeConstructor'**
While the feedback for human users is mostly the same, it does in fact matter for the LSP since the quickfix will be different depending on whether we look for a top-level identifier or if we look for a constructor.
The typical case we see in the stdlib is the `VerificationKey` and `Script` constructors for `Credential`, often being mixed with their types counterparts in aiken/crypto!
- …

LSP Fixes 

---

CHANGELOG.md
crates/aiken-lang/Cargo.toml
crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/builtins.rs
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser/chain/field_access.rs
crates/aiken-lang/src/parser/chain/mod.rs
crates/aiken-lang/src/parser/expr/chained.rs
crates/aiken-lang/src/parser/expr/record.rs
crates/aiken-lang/src/parser/pattern/constructor.rs
crates/aiken-lang/src/parser/pattern/mod.rs
crates/aiken-lang/src/parser/pattern/snapshots/constructor_module_select.snap
crates/aiken-lang/src/parser/pattern/snapshots/constructor_type_select.snap
crates/aiken-lang/src/parser/pattern/var.rs
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tests/format.rs
crates/aiken-lang/src/tests/snapshots/types_as_namespace.snap
crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/infer.rs
crates/aiken-lang/src/tipo/pattern.rs
crates/aiken-project/src/error.rs

Introduces support for using types as namespaces to access constructors in patterns and value construction. This simplifies the import management; especially for types with many constructors. It can get quite cumbersome to have to import each constructor independently. 
Note however that **this change does NOT introduce a proper _name scoping_** for constructor variants. So we're still bound to requiring unique variant names per module, even if they belong to different types. Doing so requires another set of changes which I am not necessarily willing to explore now (as they're much more _risky_ and spans over more areas, unfortunately). Yet, this changes certainly paves the way for this if we want to later.

Types as namespaces

---

CHANGELOG.md
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tipo/pattern.rs

Wrongly suggesting args in lexicographical order instead of definition order... The tests were unfortunately only examplifying situations where the fields where also defined in lexicographical order... thus never really showing the issue. It came up in the real world, though. Whoopsie.

Fix hint when suggesting to use named fields

---

CHANGELOG.md
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/parser/expr/block.rs
crates/aiken-lang/src/parser/expr/snapshots/sequence_then_expr.snap
crates/aiken-lang/src/parser/expr/snapshots/sequence_then_sequence.snap

Without this fix, the parser wrongly turns the following:
```
{
let a = Void
a
}
let _ = True
True
```
into the following:
```
let a = Void
a
let _ = True
True
```
Which in this particular example looks benign. But now takes something
more _real-world_:
```
{
let scope, output <- for_each_2(scopes, other_outputs)
Void
}
let _ = True
True
```
This would lead to the the entire sequence that follows the
backpassed continuation to be added to the continuation; here
ultimately causing a type unification error (since for_each_2 is
expected to yield Void, not Bool).
This is utterly confusing.. and dangerous.

Fix adjacent sequence collapse in parser

---

CHANGELOG.md
crates/aiken-lang/src/tests/check.rs
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/infer.rs

- :round_pushpin: **Correctly infer Fuzzer & Sampler via type annotations when referring to foreign types.**
Not sure for how long this has been broken since we basically never annotate fuzzers; but as it turns out, this wouldn't work. The is_logically_equal here is also unnecessary since we do actually have *types*, so we can leverage them directly which nicely solves the issue.
The original issue came from the module's name inferred by the annotation.
- :round_pushpin: **cleanup (no longer needed, and wrong) fuzzer annotation**
Still, keep the underlying checks about forbidden types at the boundary.

Fix fuzzer via annotation

---

CHANGELOG.md
crates/aiken-lang/src/expr.rs
crates/aiken-lang/src/test_framework.rs
crates/aiken-lang/src/tipo.rs
crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lang/src/tipo/expr.rs
crates/aiken-lang/src/tipo/pattern.rs
crates/aiken-project/src/blueprint/validator.rs
crates/aiken-project/src/test_framework.rs
examples/acceptance_tests/122/aiken.toml
examples/acceptance_tests/122/lib/tests.ak

The problem occurs for linked vars holding lists, tuples or pairs. Before this commit, the compiler will panic with:
```
crates/aiken-lang/src/test_framework.rs:1222:26
failed to reify counterexample?: "invalid type annotation. expected List but got: App { public: true, contains_opaque: false, module: \"\", name: \"Data\", args: [], alias: Some(TypeAliasAnnotation { module: Some(\"tests\"), alias: \"Redeemer\", parameters: [], annotation: Constructor { location: 52..56, module: None, name: \"Data\", arguments: [] } }) }"
```

Allow type reification to pierce through list-like Data aliases (e.g. Redeemer)

---

crates/aiken/src/cmd/benchmark.rs
crates/aiken/src/cmd/blueprint/address.rs
crates/aiken/src/cmd/blueprint/apply.rs
crates/aiken/src/cmd/blueprint/convert.rs
crates/aiken/src/cmd/blueprint/hash.rs
crates/aiken/src/cmd/blueprint/mod.rs
crates/aiken/src/cmd/blueprint/policy.rs
crates/aiken/src/cmd/build.rs
crates/aiken/src/cmd/check.rs
crates/aiken/src/cmd/completion/mod.rs
crates/aiken/src/cmd/completion/shell.rs
crates/aiken/src/cmd/docs.rs
crates/aiken/src/cmd/export.rs
crates/aiken/src/cmd/fmt.rs
crates/aiken/src/cmd/lsp.rs
crates/aiken/src/cmd/new.rs
crates/aiken/src/cmd/packages/add.rs
crates/aiken/src/cmd/packages/mod.rs
crates/aiken/src/cmd/packages/upgrade.rs
crates/aiken/src/cmd/tx/mod.rs
crates/aiken/src/cmd/tx/simulate.rs
crates/aiken/src/cmd/uplc/decode.rs
crates/aiken/src/cmd/uplc/encode.rs
crates/aiken/src/cmd/uplc/eval.rs
crates/aiken/src/cmd/uplc/fmt.rs
crates/aiken/src/cmd/uplc/mod.rs
crates/aiken/src/cmd/uplc/shrink.rs

Somehow, recent clap versions are now automatically adding a `--version` flag to all commands and sub-commands. On top of that, there's a debug assertion that makes the compiler crash should we use the `add` or `package upgrade` commands.
```
/Users/ktorz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.27/src/builder/debug_asserts.rs:86:13
Command add: Argument names must be unique, but 'version' is in use by more than one argument or group (call `cmd.disable_version_flag(true)` to remove the auto-generated `--version`)
```
Note that it's only a `debug_assert!`, and so the latest release is _fine_. But the behaviour is odd and the extra --version flag not really meaningful. So I've dropped it from all commands and sub-commands so that only the top-level binary has a …

disable '--version' flag on sub-commands

---

CHANGELOG.md
crates/aiken-lang/src/builtins.rs
crates/aiken-lang/src/tests/check.rs
crates/aiken-project/src/tests/gen_uplc.rs

New prelude function to conveniently upcast any serialisable type into `Data` in places where the compiler cannot do it implicitly.
See also: https://github.com/aiken-lang/prelude/pull/11
> [!NOTE]
> I fancied for a second introducing a new language syntax for this, like:
>
> ```aiken
>  type Foo {
>      foo: Int
>  }
>  type Bar {
>     bar: Int
>  }
>
>  test foo() {
>    [~Foo(14), ~Bar(42)] != []
>  }
> ```
> 
> But that felt a bit overkill on top of making the language more complex. The `as_data` function is already fully erase at build time, so it has the same effects anyway.

Introduce as_data in prelude

---

CHANGELOG.md
crates/aiken-lsp/src/server/lsp_project.rs
crates/aiken-project/src/lib.rs
crates/aiken-project/src/options.rs
crates/aiken-project/src/telemetry.rs
crates/aiken-project/src/telemetry/terminal.rs
crates/aiken/src/cmd/check.rs

For switching the coverage denominator between the number of iterations and the total number of labels.
```
-P, --property-coverage <COVERAGE_MODE>
Display options for the coverage.
- relative-to-labels:
Ratio of each label over the total number of labels.
Better when labels are mutually-exclusive and present in each test.
- relative-to-tests:
Ratio of each label over the total number of tests/iterations.
Better when labels are occasional and non-exclusive per test.
[default: relative-to-labels]
```
e.g.
<details><summary>-P relative-to-labels</summary>
```
┍━ check_badges.test ━━━━━━━━━━━━━━━━━━━━━━━━━━
│ PASS [after 100 tests] prop_scenario_coverage
│ · with coverage
│ | O.K.  57.0%
│ | K.O.  43.0%
│ PASS [after 100 tests] prop_check_badges_ok
│ · with coverage
│ | · at least one spent …
```

New `--property-coverage` flag to the `check` command

---

CHANGELOG.md
crates/aiken-lang/src/ast.rs
crates/aiken-lang/src/format.rs
crates/aiken-lang/src/parser.rs
crates/aiken-lang/src/parser/definition/import.rs
crates/aiken-lang/src/parser/definition/snapshots/import_alias.snap
crates/aiken-lang/src/parser/definition/snapshots/import_basic.snap
crates/aiken-lang/src/parser/definition/snapshots/import_unqualified.snap
crates/aiken-lang/src/snapshots/can_handle_comments_at_end_of_file.snap
crates/aiken-lang/src/snapshots/merge_imports.snap
crates/aiken-lang/src/snapshots/windows_newline.snap
crates/aiken-lang/src/tipo/environment.rs
crates/aiken-lsp/src/edits.rs
crates/aiken-lsp/src/quickfix.rs

- :round_pushpin: **Fix module's inhabitant import quickfix for renamed modules.**
For example, trying to use quickfix _import Foo from foo_ in a module
that looks like:
```aiken
use foo.{Bar} as renamed
```
would result in:
```aiken
use foo.{Bar} as renamed.{Foo}
```
instead of:
```aiken
use foo.{Bar, Foo} as renamed
```
This is now fixed, although only tested manually since we don't have
any good ways of automatically testing the LSP quickfixes...
- :round_pushpin: **Fix quickfix suggestion to use qualified for renamed modules.**
When a module is declared as:
```
use foo as renamed
```
We would otherwise wrongly suggest to _import Foo from foo_, instead
of correctly suggesting to _import Foo from renamed_.
This commit fixes it.

Lsp quickfixes renamed imports

---

CHANGELOG.md
crates/aiken-lang/src/tipo/error.rs
crates/aiken-lang/src/tipo/hydrator.rs
crates/aiken-lang/src/tipo/infer.rs
crates/aiken-lsp/README.md
crates/aiken-lsp/src/edits.rs
crates/aiken-lsp/src/quickfix.rs

- :round_pushpin: **New quickfix for automatically plucking inferred types in holes within annotations.**
- :round_pushpin: **New quickfix to automatically make functions and constants public when detected unused.**
- :round_pushpin: **New quickfix to make types public when 'leaking' from a public function (e.g. validator handlers)**
Also improved the error message when detecting a leaking type through
an aliased type. Now display both the alias and the source type, for
clarity.
- :round_pushpin: **Also enable unused quickfix for types.**

Lsp pub and pluck quickfixes

---

crates/aiken-project/src/blueprint/error.rs
crates/aiken-project/src/blueprint/mod.rs
crates/aiken-project/src/error.rs
crates/aiken-project/src/lib.rs
crates/aiken-project/src/watch.rs
crates/aiken/src/cmd/blueprint/apply.rs
crates/aiken/src/cmd/blueprint/convert.rs

The goal of this change is to enable calling `aiken blueprint apply --in some/plutus.json` from outside of an Aiken project. This is especially useful when needing to apply parameters on a contract written by someone else, or simply from another directory.

Move parameter application into the blueprint module

---

crates/aiken-project/src/lib.rs

Having `.md` files within folders is something I find desirable as it allows a more organized documentation. This PR filters the files considered in an Aiken project, so that only `.ak` files are checked.
In full disclosure, I'm not a Rust dev. AI initially suggested `.map_or()`, but `clippy` recommended `.is_some_and()` instead.

Ignore Non-`ak` Files in `check`

---

flake.lock
flake.nix

And also, avoid building and running tests when building through Nix; that's needlessly long. Note also that the _real_ problem was that the 'flake.lock' was outdated and needed refresh.
Fixes #1188.

Fix nix flake: pull rust-version from Cargo.toml

---

crates/aiken-lang/src/gen_uplc/decision_tree.rs
examples/acceptance_tests/125/aiken.toml
examples/acceptance_tests/125/lib/thing.ak

Fixes an issue where aliasing a constr variant like VerificationKey as VerificationKeyContstructor would cause the compiler to crash if you use VerificationKeyContstructor in a when

Alias constr variant compiler crash fix

---

CHANGELOG.md
Cargo.lock
Cargo.toml

closes #1176 
@KtorZ seems to have fixed this already in pallas directly here https://github.com/txpipe/pallas/commit/cefc5abee1736258b16899e6809b8fddfe946f86
and it was released in 0.33.0 of pallas.
I think this means we just need to bump the pallas version to close this issue.

PlutusData comparison in the UPLC VM shouldn't rely on CBOR encoding
