aiken-lang/aiken

- crates/cli/src/main.rs
- crates/uplc/src/ast.rs
- crates/uplc/src/debruijn.rs
- crates/uplc/src/debruijn/bimap.rs
- crates/uplc/src/test.rs
closes #1 
* https://github.com/input-output-hk/plutus/blob/master/plutus-core/plutus-core/src/PlutusCore/DeBruijn/Internal.hs
* https://github.com/input-output-hk/plutus/blob/master/plutus-core/untyped-plutus-core/src/UntypedPlutusCore/DeBruijn.hs
> convert a named debruijn to a name

- Cargo.lock
- crates/cli/src/args.rs
- crates/cli/src/main.rs
- crates/uplc/Cargo.toml
- crates/uplc/src/builtins.rs
- crates/uplc/src/debruijn.rs
- crates/uplc/src/lib.rs
- crates/uplc/src/pretty.rs
- crates/uplc/src/test.rs
- crates/uplc/test_data/basic/integer/integer.uplc
> pretty printing

- .github/workflows/rust.yml
https://github.com/txpipe/aiken/issues/7
> Add CI to the Repository

- crates/uplc/src/debruijn.rs
- crates/uplc/src/debruijn/bimap.rs
- crates/uplc/tests/integ_tests.rs
> fix issue with same names causing 0 index debruijn for var

- crates/uplc/src/machine.rs
- crates/uplc/src/machine/error.rs
Co-authored-by: rvcas <x@rvcas.dev>
> switch to stack model for plutus eval

- Cargo.lock
- add_integers.uplc
- crates/flat/src/decode/decoder.rs
- crates/flat/src/encode/encoder.rs
- crates/uplc/Cargo.toml
- crates/uplc/src/ast.rs
- crates/uplc/src/flat.rs
- crates/uplc/src/machine.rs
- crates/uplc/src/machine/error.rs
- crates/uplc/src/machine/runtime.rs
- crates/uplc/src/pretty.rs
> feat: add some missing enum members to constant

- .envrc
- .github/workflows/build_nix.yml
- default.nix
- flake.lock
- flake.nix
- shell.nix
Commit created with `nix flake init --template github:nixos/templates#rust`.
GitHub Action comes for free.
> feat: add a nix flake

- Cargo.lock
- add_integers.uplc
- crates/uplc/Cargo.toml
- crates/uplc/src/machine.rs
- crates/uplc/src/machine/cost_model.rs
- crates/uplc/src/machine/error.rs
- crates/uplc/src/machine/runtime.rs
Co-authored-by: rvcas <x@rvcas.dev>
> Add several builtins for strings and bytestring

- Cargo.lock
- crates/flat/Cargo.toml
- crates/flat/src/encode/encoder.rs
- crates/flat/src/lib.rs
- crates/flat/src/zigzag.rs
- crates/flat/tests/flat_test.rs
- crates/flat/tests/zigzag_test.rs
fixes clippy check issues for forked repo
> Fix clippy zypeh

- Cargo.lock
- crates/flat/Cargo.toml
- crates/flat/tests/flat_test.rs
- crates/flat/tests/zigzag_test.rs
> Rewrite test in proptest, removing Quickcheck dependency

- add_integers.uplc
- crates/cli/src/args.rs
- crates/cli/src/main.rs
- crates/uplc/src/ast.rs
- crates/uplc/src/parser.rs
> eval with inputs

- crates/uplc/src/tx/error.rs
- crates/uplc/src/tx/eval.rs
It could be useful to know which redeemer caused the error.
e.g.: `"Redeemer (Cert, 0): Missing required script: 0b61cc751e9512fef62362f00e6db61e70d719a567c6d4eb68095957"`
> Wrap errors in redeemer error

- README.md
- book/src/SUMMARY.md
- book/src/components.md
- book/src/introduction.md
- book/src/resources.md
- book/src/uplc.md
- Move some of the sections from the readme to the book.
- add a more defined roadmap and goals section to the book intro
> chore: update readme and book

- book/src/introduction.md
typechecking and inference is done for now
> chore: update roadmap

- CHANGELOG.md
- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/cmd/lsp.rs
- crates/cli/src/cmd/mod.rs
- crates/cli/src/main.rs
- crates/lang/src/tipo/environment.rs
- crates/lang/src/uplc.rs
- crates/lsp/Cargo.toml
- crates/lsp/src/lib.rs
- crates/uplc/src/debruijn.rs
This is a basic start to the language server. I mostly followed some examples from rust-analyzer and gleam.
Currently it only supports formatting.
There is a corresponding vscode extension in a separate repo.
> Start Aiken Language Server

- .editorconfig
- book/src/SUMMARY.md
- book/src/getting-started.md
- :round_pushpin: **Add .editorconfig, covering only \*.ak file for now.**
- :round_pushpin: **Add 'getting-started' first draft.**
Mostly to have a place to list editors integrations.
> Add .editorconfig, covering only *.ak file for now.

- .github/ISSUE_TEMPLATE/bug.md
macOS is now at version 13 :smiley:
> replace OSX with macOS in the issue template

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/cmd/error.rs
- crates/cli/src/cmd/mod.rs
- crates/cli/src/cmd/new.rs
> Validate project name on `aiken new`

- crates/lang/src/builtins.rs
- crates/lang/src/tipo/environment.rs
add new Data type to prelude and allow it to unify with any user defined type
> Add `Data` to prelude

- crates/lang/src/ast.rs
- crates/lang/src/format.rs
- crates/lang/src/parser.rs
- crates/lang/src/parser/lexer.rs
- crates/lang/src/parser/token.rs
- crates/lang/src/tipo/expr.rs
- crates/lang/src/tipo/infer.rs
- crates/lang/src/tipo/pattern.rs
- examples/sample/validators/swap.ak
* we need to be able to cast raw `Data` as any type using assignment
* general parser fixes
* add a new check keyword that is a more thorough assert in a way
> Casting and Parser fixes

- book/src/uplc/syntax.md
- examples/aiken_std/lib/aiken/list.ak
I'd love to get some ways to write and run some basic unit tests in Aiken. I've sketched out a few tests in comment and it could be nice to have. I am thinking that running tests should also display the execution units as a way to guide us in how to implement an efficient standard lib. For example, I've purposely not used some higher-level functions like `foldr` in some places and went straight to basic recursion because of performance consideration. Similarly, some function can be short-circuited if written with recursion + if/then/else. 
I've also excluded a few functions from now which works with pairs / tuples until this is also supported by the compiler.
> Implement standard library for lists.

- crates/project/src/error.rs
- crates/project/src/lib.rs
this is a bit hacky and wastes some s
pace but it works fine
> Display file name in cli errors

- crates/cli/src/cmd/build.rs
- crates/project/src/lib.rs
- `uplc` to optionally dump raw uplc
> Optionally dump raw uplc on build

- crates/lang/src/ast.rs
- crates/lang/src/format.rs
- crates/lang/src/parser.rs
- crates/lang/src/parser/error.rs
- crates/lang/src/tipo/error.rs
- crates/lang/src/tipo/expr.rs
- crates/project/src/error.rs
- examples/sample/validators/swap.ak
```gleam
const something = 5
const something: ByteArray = #[12, 32]
```
> Module Constants

- crates/lang/src/format.rs
- crates/lang/src/tipo/environment.rs
- examples/aiken_std/lib/aiken/context.ak
- examples/aiken_std/lib/aiken/map.ak
- tuples were missing a case in environment.unify
- formatter bug with records
- add map to stdlib
> Unify Tuples

- README.md
> update link to user manual

- crates/lang/src/ast.rs
- crates/project/src/lib.rs
This function can be moved out of project
> Refactor move helper option builder to lang

- crates/lang/src/builtins.rs
- crates/lang/src/expr.rs
- crates/lang/src/tipo.rs
- crates/lang/src/uplc.rs
- examples/acceptance_tests/019/lib/test.ak
- examples/acceptance_tests/025/lib/test.ak
* nothing special really, just a boring rename
closes #203
> rename Nil to Unit

- crates/aiken/src/cmd/error.rs
- crates/aiken/src/cmd/new.rs
> `aiken new` command

- crates/aiken-lang/src/format.rs
- crates/aiken-lang/src/tests/format.rs
- crates/aiken-lang/src/tests/mod.rs
> Fix formatting of if-expressions

- crates/aiken-lang/src/air.rs
- crates/aiken-lang/src/builder.rs
- crates/aiken-lang/src/uplc.rs
- crates/aiken-project/src/lib.rs
- crates/uplc/src/ast.rs
- crates/uplc/src/ast/builder.rs
- examples/sample/validators/swap.ak
includes some needed fixes for zero arg functions
> Nested tuples in when produces uplc. Also a few define ir fixes for function dependence

- crates/aiken-lang/src/air.rs
- crates/aiken-lang/src/ast.rs
- crates/aiken-lang/src/expr.rs
- crates/aiken-lang/src/format.rs
- crates/aiken-lang/src/parser.rs
- crates/aiken-lang/src/parser/lexer.rs
- crates/aiken-lang/src/tipo/expr.rs
- crates/aiken-lang/src/uplc.rs
* add unary op
* parse, typecheck, and code gen it
* express boolean not as unary op as well, previously called negate
closes #221
> support negation of int

- crates/aiken-lang/src/builder.rs
- crates/aiken-lang/src/tipo/expr.rs
- crates/aiken-lang/src/uplc.rs
- examples/acceptance_tests/031/lib/tests.ak
> Acceptance tests 31 and 28 and minor scope fixes with sequence

- crates/aiken-lang/src/builder.rs
- crates/aiken-lang/src/uplc.rs
Can now use int, bytearray, string, assoclist, list as a validator param and pass in data 
closes #228
> validator params are now converted to type from data

- crates/aiken-lang/src/ast.rs
- crates/aiken-lang/src/builder.rs
- crates/aiken-lang/src/uplc.rs
- crates/uplc/src/machine/error.rs
- crates/uplc/src/machine/runtime.rs
- examples/acceptance_tests/035/lib/aiken/dict.ak
- examples/acceptance_tests/035/lib/tests.ak
Fixes issues with function dependency and variant name. Should fix all the free unique problems.
Also includes more cases where users can see type hint
Aiken VM will include undata builtin in plutus data deserialization errors
closes #230
> Acceptance test 35 and 36 (mostly). 

- crates/aiken-lang/src/air.rs
- crates/aiken-lang/src/builder.rs
- crates/aiken-lang/src/uplc.rs
Issue with using ListClause in nested lists inside a when. Fixed by adding a new Air: ListClauseGuard. 
Removed unnecessary discard paired with ListClause.
> fix: nested list issues in when statements

- .github/workflows/rust.yml
- crates/aiken-lang/src/air.rs
- crates/aiken-lang/src/builder.rs
- crates/aiken-lang/src/uplc.rs
- Booleans inside a list now produce the correct cbor
- Nested lists now produce the correct ir
- ListClause and ListClauseGuard expect a discard to pop off (might remove later)
- Closes #239
> Nested list fix and Boolean constant fix

- CHANGELOG.md
- Cargo.lock
- crates/aiken-lang/src/parser.rs
- crates/aiken-lang/src/uplc.rs
- crates/aiken-project/Cargo.toml
- crates/aiken-project/src/lib.rs
- crates/aiken-project/src/script.rs
- some clippy fixes
- add rayon to `aiken-project`
- use rayon to run tests in parallel
> Parallel Test Execution

- crates/aiken-lang/src/uplc.rs
> English auction discard assignment fix

- crates/aiken-lang/src/tipo.rs
- crates/aiken-lang/src/tipo/error.rs
- crates/aiken-lang/src/tipo/infer.rs
- examples/acceptance_tests/040/aiken.toml
closes #261 
```aiken
type Foo {
bar: fn(Int) -> Int
}
```
Will now return errors that look like this:
> Error for Function in DataType

- crates/aiken-lang/src/air.rs
- crates/aiken-lang/src/builder.rs
- crates/aiken-lang/src/uplc.rs
Now opaque types with one constr and one field are converted to inner field type
> Change single constr opaque types to their inner types

- crates/aiken-lang/src/uplc.rs
> feat: handle anon zero arg functions

- crates/aiken-lang/src/tipo/error.rs
- crates/aiken-lang/src/tipo/expr.rs
> Single when clause should be a `let` warning

- crates/uplc/src/machine/runtime.rs
Forgot to change the `k256` schnorr function. I got a bit confused myself yesterday. Also added a small comment explaining  our current approach.
> Fixed schnorr and limiting it to 32 bytes messages for now

- crates/uplc/src/machine/runtime.rs
Sorry @KtorZ, here are the unit tests for tag/constructor conversions.
> Added tag/constructor conversion tests

- crates/aiken-lang/src/uplc.rs
> scope is now properly handled in expect cases that call a function on the RHS

- crates/aiken-lang/src/uplc.rs
- examples/acceptance_tests/040/lib/tests.ak
Add case to acceptance test 40
Add special case for top level single constructor in a when.
> feat: handle single constr when with multiple branches

- crates/aiken-project/src/blueprint/schema.rs
- crates/aiken-project/src/blueprint/validator.rs
* the test from before never actually used foo so it did not trigger the error
> Data as field in Datum

- examples/hello_world/.vscode/settings.json
- examples/hello_world/README.md
- examples/hello_world/generate-credentials.ts
- examples/hello_world/hello_world-lock.ts
- examples/hello_world/hello_world-unlock.ts
- added missing types
- updated variable names and log messages
- addressed inconsistencies between the documentation and the code
- ran deno fmt
> Update hello_world example

- crates/aiken-project/src/lib.rs
closes #429 
* filtering was moved from `Project::eval_scripts` to `Project::collect_tests`
> filter tests before code gen

- examples/gift_card/deno.lock
- examples/gift_card/islands/App.tsx
- flake.lock
- flake.nix
Chose to use nixos unstable otherwise version is lagging.
> Add Deno to nix

- crates/aiken-lang/src/gen_uplc.rs
- crates/aiken-lang/src/gen_uplc/builder.rs
- examples/acceptance_tests/048/lib/tests.ak
@MicroProofs, I found an interesting one: It seems like we don't properly handle clause guards for wildcard patterns. Seems to be a codegen issue here as the code type-check properly.
> Add new failing test case for 048 (clause guards)

- crates/aiken-project/src/tests/gen_uplc.rs
- crates/uplc/src/builder.rs
- crates/uplc/src/optimize.rs
- crates/uplc/src/optimize/shrinker.rs
- Convert acceptance test 8
- Adds a minor optimization to go from 
[
(lam a a)
[(builtin headList) xs]
]
to
[(builtin headList) xs]
> Convert acceptance test 8 and more

- Cargo.nix
- flake.lock
- flake.nix
> Cargo.nix, cargo2nix bump

- crates/uplc/src/pretty.rs
> Fix dumping of builtin pairs in lists

- crates/aiken-lang/src/gen_uplc.rs
- crates/aiken-project/src/tests/gen_uplc.rs
Fix record updates to actually work
Create comprehensive tests for record update with varying scenarios 
Closes #557
> Record update fix

- crates/aiken-lang/src/tipo/error.rs
closes #548 
* if expected and given are equal then we show the module
* we could do it in all cases it looks kinda nice
* format is `Type - ModuleName`
> add module name to type mismatch error

- crates/aiken-lang/src/gen_uplc.rs
- crates/aiken-lang/src/gen_uplc/builder.rs
fix: rearrange clauses and fill in gaps now handles nested patterns in a uniform way
fix: discards in records was being sorted incorrectly leading to type issues
chore: remove some filter maps in cases where None is impossible anyway
chore: some refactoring on a couple functions to clean up
> fixes: For various code gen issues

- .gitignore
- crates/aiken/src/main.rs
- flake.nix
A bit tidier with squashed commit
> fix: git rev in version when built with nix

- CHANGELOG.md
- crates/aiken-lang/src/gen_uplc.rs
- examples/acceptance_tests/084/lib/tests.ak
> fix: builtins using the incorrect data to type conversion when used as a function param.

- CONTRIBUTING.md
I'm a bit new to nix, and this wasn't super obvious to me, so I figured mentioning it in the CONTRIBUTING.md might help other new contributors too
> Mention nix develop in CONTRIBUTING.md

- crates/aiken-lang/src/builtins.rs
- crates/aiken-lang/src/format.rs
- crates/aiken-lang/src/tests/check.rs
- crates/aiken-lang/src/tipo.rs
- crates/aiken-lang/src/tipo/environment.rs
- crates/aiken-lang/src/tipo/error.rs
- crates/aiken-lang/src/tipo/exhaustive.rs
- crates/aiken-lang/src/tipo/expr.rs
- crates/aiken-lang/src/tipo/expr/usefulness.rs
this implements exhaustiveness checking by borrowing code from Elm and Rust. Both reference http://moscova.inria.fr/~maranget/papers/warn/index.html
closes #657
closes #656
closes #629
> Exhaustiveness Checking

- crates/aiken-lang/src/gen_uplc.rs
- crates/aiken-lang/src/gen_uplc/air.rs
- crates/aiken-lang/src/gen_uplc/builder.rs
- crates/aiken-lang/src/gen_uplc/tree.rs
- crates/aiken-project/src/tests/gen_uplc.rs
Added some new tests targeted around list clauses
Performed some minor fixes on code gen
> Air tree list tests

- crates/uplc/src/parser.rs
- crates/uplc/src/pretty.rs
- crates/uplc/tests/pretty_tests.rs
> Fix pretty prenting and parsing of strings with escaped values in complex data structures

- crates/aiken-lang/src/gen_uplc.rs
- crates/aiken-lang/src/gen_uplc/builder.rs
Also refactor list_access_to_uplc to actually be readable
> refactor: change codegen uplc to have more type safety

- crates/uplc/src/machine/runtime.rs
- crates/uplc/src/parser.rs
- crates/uplc/src/pretty.rs
- crates/uplc/test_data/conformance/evaluation/builtin/semantics/constrData/constrData.uplc
- crates/uplc/test_data/conformance/evaluation/builtin/semantics/constrData/constrData.uplc.expected
- crates/uplc/tests/pretty_tests.rs
> Fix incorrect parsing and printing of CBOR Tags

- flake.nix
> Add additional CoreServices dependency when building on macOS

- crates/aiken-project/src/config.rs
> fix: aiken new github action version

- CHANGELOG.md
- crates/aiken-lang/src/ast.rs
- crates/aiken-lang/src/builtins.rs
- crates/aiken-lang/src/gen_uplc.rs
- crates/aiken-lang/src/gen_uplc/builder.rs
- crates/aiken-lang/src/tipo.rs
- crates/aiken-lang/src/tipo/environment.rs
- crates/aiken-lang/src/tipo/error.rs
- crates/aiken-lang/src/tipo/hydrator.rs
- crates/aiken-lang/src/tipo/infer.rs
- crates/aiken-project/src/blueprint/snapshots/aiken_project__blueprint__validator__tests__annotated_data.snap
- crates/aiken-project/src/blueprint/validator.rs
- crates/aiken-project/src/tests/gen_uplc.rs
If we decide to go this route, this pr also makes discards check for the type. The one thing I would encourage for this to be accepted is for some way to specify Data < T >, where T is the type you want to show up in the blueprint, but don't want expensive type checking to be run.
Closes #814
> Discards will now check for type too.

- Cargo.lock
- crates/aiken-project/Cargo.toml
> update package dependency

- CHANGELOG.md
- Cargo.lock
- crates/aiken-lang/Cargo.toml
- crates/aiken-lang/src/ast.rs
- crates/aiken-lang/src/expr.rs
- crates/aiken-lang/src/line_numbers.rs
- crates/aiken-lang/src/parser/extra.rs
- crates/aiken-lang/src/parser/token.rs
- crates/aiken-lang/src/tipo.rs
- crates/aiken-lang/src/tipo/expr.rs
- crates/aiken-lang/src/tipo/fields.rs
- crates/aiken-project/Cargo.toml
- crates/aiken-project/src/lib.rs
- crates/aiken-project/src/module.rs
- crates/uplc/src/builtins.rs
~We want to cache the typed ast of all compiled modules from dependencies but not the main project itself~
for now we are going to just impl serde on CheckedModule and then in the future we can use `ciborium` to cache deps to disk.
> impl serde on CheckedModule

- crates/aiken-lang/src/tests/check.rs
- crates/aiken-lang/src/tipo.rs
- crates/aiken-lang/src/tipo/environment.rs
> Fixes #881.

- flake.lock
- flake.nix
^
I also ran a formatter which is why the diff looks bad. 
```
nix run github:kamadorueda/alejandra/3.0.0 flake.nix
```
> bump nix: use rustc 1.79, add analyzer to devshell

- flake.lock
- flake.nix
Everyone's favourite PR. 
+ bump nixpkgs for latest stable rust toolchain 
+ fix patch in nix build
> bump flake

- crates/uplc/src/machine/cost_model.rs
Fix and use cost model tests to ensure everything is up to date with the current mainnet cost model
> Cost model fixes with tests

- examples/hello_world/generate-credentials.ts
- examples/hello_world/package.json
Minor update and include package.json
```
hello_world % npx tsx lock.ts 
1 tADA locked into the contract at Tx ID: 454e8f03540a3cff3ec471749111d555b3bd5b0fd00c450f0f5ec6e8c3084f5d
hello_world % npx tsx unlock.ts 454e8f03540a3cff3ec471749111d555b3bd5b0fd00c450f0f5ec6e8c3084f5d 
1 tADA unlocked from the contract at Tx ID: 5acef4556f5bdacdc2b9ff3c923a026f5f8a3ab0525f412ebf01d96d9d88933e
```
> update code and include package.json

- crates/aiken/src/cmd/completion/mod.rs
Encountered this copy & paste error when using aiken.
> Fix completion cli documentation

- CHANGELOG.md
- crates/aiken-lang/src/tests/check.rs
- crates/aiken-lang/src/tipo/error.rs
- crates/aiken-lang/src/tipo/pattern.rs
- crates/aiken-lsp/src/quickfix.rs
Fixes #1084 
> [!NOTE]
>
> Include an LSP quickfix to automatically fix the warning.
> Destructure record fields warning

- Cargo.lock
- Cargo.toml
- crates/aiken-lang/Cargo.toml
- crates/aiken-lang/src/builtins.rs
- crates/aiken/Cargo.toml
- crates/aiken/src/cmd/uplc/eval.rs
- crates/uplc/Cargo.toml
- crates/uplc/src/ast.rs
- crates/uplc/src/builtins.rs
- crates/uplc/src/machine.rs
- crates/uplc/src/machine/cost_model.rs
- crates/uplc/src/machine/eval_result.rs
- crates/uplc/src/machine/runtime.rs
This will help ensure our costing matches the haskell one.
> Add a debug flag for uplc eval

- CHANGELOG.md
- Cargo.lock
- crates/aiken-project/Cargo.toml
- crates/aiken-project/src/telemetry/terminal.rs
> reintroduce bench graph borders

- CHANGELOG.md
- crates/aiken-lang/src/format.rs
- crates/aiken-project/src/watch.rs
- crates/aiken/src/cmd/benchmark.rs
- crates/aiken/src/cmd/blueprint/address.rs
- crates/aiken/src/cmd/blueprint/apply.rs
- crates/aiken/src/cmd/blueprint/hash.rs
- crates/aiken/src/cmd/blueprint/policy.rs
- crates/aiken/src/cmd/build.rs
- crates/aiken/src/cmd/check.rs
- crates/aiken/src/cmd/docs.rs
- crates/aiken/src/cmd/export.rs
> some adjustments

- CHANGELOG.md
- crates/aiken-lang/src/parser/expr/record.rs
- examples/acceptance_tests/121/aiken.toml
- examples/acceptance_tests/121/lib/tests.ak
Compiler said I couldn't do it, so I changed the compiler.
> Allow captures within constructor calls.

- crates/aiken-lang/src/ast.rs
- crates/aiken-lang/src/gen_uplc.rs
- crates/aiken-lang/src/gen_uplc/builder.rs
- crates/aiken-lang/src/gen_uplc/decision_tree.rs
- crates/aiken-lang/src/gen_uplc/stick_break_set.rs
- crates/aiken-lsp/src/edits.rs
- crates/aiken-lsp/src/quickfix.rs
- crates/aiken-project/src/blueprint/error.rs
- crates/aiken-project/src/config.rs
- crates/aiken-project/src/pretty.rs
- crates/aiken-project/src/tests/gen_uplc.rs
- crates/aiken-project/src/watch.rs
- crates/aiken/src/cmd/blueprint/apply.rs
- crates/aiken/src/cmd/blueprint/policy.rs
- crates/aiken/src/cmd/completion/shell.rs
- crates/aiken/src/cmd/export.rs
- crates/uplc/src/flat.rs
- crates/uplc/src/optimize/shrinker.rs
- examples/acceptance_tests/124/aiken.toml
- examples/acceptance_tests/124/lib/tests.ak
> Decision tree hoist edge case with empty scope

- CHANGELOG.md
- crates/aiken-lang/src/format.rs
- crates/aiken-lang/src/tests/format.rs
- crates/aiken-lang/src/tests/snapshots/long_import_line.snap
- crates/aiken-lang/src/tests/snapshots/long_import_line_2.snap
> formatting for long import lines

- CHANGELOG.md
- crates/aiken-project/src/package_name.rs
- crates/aiken/src/cmd/packages/add.rs
> aiken add wrongly rejects valid org/repo names
